---
title: "GSE66664_dermalPapillaAnalysis"
author: "Bruna Garbes"
date: "6 de abril de 2018"
output: html_document
---


```{r}
# Display the current working directory
getwd();
# If necessary, change the path below to the directory where the data files are stored.
# "." means current directory. On Windows use a forward slash / instead of the usual \.
workingDir = ".";
setwd(workingDir);
# Load the package
library(WGCNA);
library(plyr);
library(dplyr);
library(readr);
library(magrittr);
library(data.table);
library(readxl);
# The following setting is important, do not omit.
options(stringsAsFactors = FALSE);

```

```{r}
GSE66664_series_matrix <- read_delim("D:/estagio/WGCNA_analysis/DermalPapillaAnalysis/GSE66664_series_matrix.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
GSE66664SeriesMatrix <- GSE66664_series_matrix[2:47290,]
GSE66664SeriesMatrix <- select(GSE66664SeriesMatrix, ID_REF, num_range("GSM1627", 302:304), num_range("GSM1627",308:310), num_range("GSM1627",338:339), num_range("GSM1627",343:345),num_range("GSM1627",373:375),num_range("GSM1627",379:381),num_range("GSM1627",408:409),num_range("GSM1627",413:415))

GSE66664ID_REF_to_Ensembl <- read_delim("C:/Users/WADSONGARBESGONCALVE/Desktop/dataInputs/DermalPapillaAnalysis/GSE66664ID_REF_to_Ensembl.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE) # ID convertion performed with Biomart
colnames(GSE66664ID_REF_to_Ensembl)= c("Ensembl", "ID_REF", "GeneName")
GSE66664Data= GSE66664SeriesMatrix

write.csv(GSE66664Data, "GSE66664Data.txt", row.names = FALSE)
GSE66664Data <- read_csv("GSE66664Data.txt")
```

```{r}
variance <- apply(GSE66664Data[2:23],1,sd)/apply(GSE66664Data[2:23],1,mean)

hist(variance)
keep=as.data.frame(GSE66664Data)
rownames(keep)=keep[,1]
keep=keep[2:23]
keep2=which(apply(keep,1,sd)/apply(keep,1,mean)>= 0.025)
keep=keep[keep2,]
hist(keep)
keep3= mutate(keep, ID_REF=rownames(keep))
GSE66664Data=keep3

GSE66664Data <- merge(GSE66664Data, GSE66664ID_REF_to_Ensembl, by = c("ID_REF"))
GSE66664Data= distinct(GSE66664Data, Ensembl, .keep_all = T)
```

```{r message=FALSE, eval=FALSE}
#Our neuron data 
ruvNormDataNeuron <- read_delim("D:/estagio/WGCNA_analysis/data_comparison/countData_RUV_Normalized_Neuron_nDEGs_HKgenes_p0.4_k4.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)


KMENeuron <- read_excel("D:/estagio/WGCNA_analysis/data_comparison/kME_counts_Neurons_p0.4_k4_keep0.0125_power16_minsize150_cut0.15.xlsx")

KMENeuron <- select(KMENeuron, Symbol : moduleLabel)
colnames(KMENeuron) <- c("Gene","GeneName", "moduleColor", "moduleLabel")
ourDataNeuron <- merge(KMENeuron, ruvNormDataNeuron, by = ("Gene"))

```

```{r message=FALSE, eval=FALSE}
dat0 = ourDataNeuron
names(dat0)
# this contains information on the genes
datSummaryNeuron=dat0[,c(1:4)]
# the following data frame contains
# the gene expression data: columns are genes, rows are arrays (samples)
datExprNeuron <- t(dat0[,5:22])
no.samples <- dim(datExprNeuron)[[1]]
dim(datExprNeuron)
# Set the columns names to probe names
colnames(datExprNeuron) = datSummaryNeuron$Gene
# This module assignment was obtained by Ghazalpour et al
colorsNeuron = dat0$moduleColor
```

# Reading GSE66664Data
```{r message=FALSE, eval=FALSE}

data66664 = GSE66664Data
#symbol = select(voiData, gene_symbol)
datExpr66664 = t(data66664[,2:23]);
colnames(datExpr66664) = data66664$Ensembl

setLabels = c("Neuron", "GSE66664");
multiExpr = list(Neuron = list(data = datExprNeuron), GSE66664 = list(data = datExpr66664));
multiColor = list(Neuron = colorsNeuron);
```

##Running WGCNA module preservation analysis
```{r message=FALSE, eval=FALSE}

system.time( {
mp = modulePreservation(multiExpr, multiColor,
referenceNetworks = 1,
nPermutations = 200,
randomSeed = 1,
quickCor = 0,
verbose = 3)
} );

# Save the results
save(mp, file = "modulePreservationNeuronGSE66664.RData");

#Alternatively, if the data has already been calculated before, load them from disk:
#load(file="modulePreservationNeuronNPC.RData")
```

#Analysis and display of module preservation results
```{r message=FALSE, eval=FALSE}

ref = 1
test = 2
statsObs = cbind(mp$quality$observed[[ref]][[test]][, -1], mp$preservation$observed[[ref]][[test]][, -1])
statsZ = cbind(mp$quality$Z[[ref]][[test]][, -1], mp$preservation$Z[[ref]][[test]][, -1]);

# Compare preservation to quality:
ZscoreTable=print( cbind(statsObs[, c("medianRank.pres", "medianRank.qual")],
signif(statsZ[, c("Zsummary.pres", "Zsummary.qual")], 2)) )
```

#Plotting results
```{r message=FALSE, eval=FALSE}
# Module labels and module sizes are also contained in the results
modColors = rownames(mp$preservation$observed[[ref]][[test]])
moduleSizes = mp$preservation$Z[[ref]][[test]][, 1];
# leave grey and gold modules out
plotMods = !(modColors %in% c("grey", "gold"));
# Text labels for points
text = modColors[plotMods];
# Auxiliary convenience variable
plotData = cbind(mp$preservation$observed[[ref]][[test]][, 2], mp$preservation$Z[[ref]][[test]][, 2])
# Main titles for the plot
mains = c("Preservation Median rank", "Preservation Zsummary");
# Start the plot
sizeGrWindow(10, 5);
pdf(file ="NeuronsvsGSE66664Data-Zsummary-medianRank.pdf", wi=10, h=5)
par(mfrow = c(1,2))
par(mar = c(4.5,4.5,2.5,1))
for (p in 1:2)
{
min = min(plotData[, p], na.rm = TRUE);
max = max(plotData[, p], na.rm = TRUE);
# Adjust ploting ranges appropriately
if (p==2)
{
if (min > -max/10) min = -max/10
ylim = c(min - 0.1 * (max-min), max + 0.1 * (max-min))
} else
ylim = c(max + 0.1 * (max-min), min - 0.1 * (max-min))
plot(moduleSizes[plotMods], plotData[plotMods, p], col = 1, bg = modColors[plotMods], pch = 21,
main = mains[p],
cex = 2.4,
ylab = mains[p], xlab = "Module size", log = "x",
ylim = ylim,
xlim = c(10, 2000), cex.lab = 1.2, cex.axis = 1.2, cex.main =1.4)
labelPoints(moduleSizes[plotMods], plotData[plotMods, p], text, cex = 1, offs = 0.08);
# For Zsummary, add threshold lines
if (p==2)
{
abline(h=0)
abline(h=2, col = "blue", lty = 2)
abline(h=10, col = "darkgreen", lty = 2)
}
}
# If plotting into a file, close it
dev.off();
```

```{r message=FALSE, eval=FALSE}
# Re-initialize module color labels and sizes
modColors = rownames(statsZ)
moduleSizes = mp$quality$Z[[ref]][[test]][, 1];
# Exclude improper modules
plotMods = !(modColors %in% c("grey", "gold"));
# Create numeric labels for each module
labs = match(modColors[plotMods], standardColors(50));
# Start the plot: open a suitably sized graphical window and set sectioning and margins.
sizeGrWindow(12, 9);
par(mfrow = c(3,5))
par(mar = c(3,3,2,1))
par(mgp = c(1.6, 0.4, 0));
# Plot each Z statistic in a separate plot.
for (s in 1:ncol(statsZ))
{
min = min(statsZ[plotMods, s], na.rm = TRUE);
max = max(statsZ[plotMods, s], na.rm = TRUE);
if (min > -max/5) min = -max/5
plot(moduleSizes[plotMods], statsZ[plotMods, s], col = 1, bg = modColors[plotMods], pch = 21,
main = colnames(statsZ)[s],
cex = 1.7,
ylab = colnames(statsZ)[s], xlab = "Module size", log = "x",
ylim = c(min - 0.1 * (max-min), max + 0.1 * (max-min)),
xlim = c(20, 1000))
labelPoints(moduleSizes[plotMods], statsZ[plotMods, s], labs, cex = 0.7, offs = 0.04);
abline(h=0)
abline(h=2, col = "blue", lty = 2)
abline(h=10, col = "darkgreen", lty = 2)
}

data.frame(color = modColors[plotMods], label = labs)
```