---
title: "WGCNA_ModulePreservationAnalysis_NeuronsVsAlissonData"
author: "Bruna Garbes"
date: "6 de novembro de 2017"
output:
  word_document: default
  html_document: default
---

```{r message=FALSE, eval=FALSE}
# Display the current working directory
getwd();
# If necessary, change the path below to the directory where the data files are stored.
# "." means current directory. On Windows use a forward slash / instead of the usual \.
#workingDir = ".";
#setwd(workingDir);
#setwd("D:/estagio/WGCNA_analysis/data_comparison")
# Load the package
library(WGCNA);
library(plyr);
library(dplyr);
library(readr);
library(magrittr);
library(data.table);
# The following setting is important, do not omit.
options(stringsAsFactors = FALSE);
```

```{r message=FALSE, eval=FALSE}
#Our neuron data 
ruvNormDataNeuron <- read_delim("D:/estagio/WGCNA_analysis/data_comparison/countData_RUV_Normalized_Neuron_nDEGs_HKgenes_p0.4_k4.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

KMENeuron <- read_excel("D:/estagio/WGCNA_analysis/data_comparison/kME_counts_Neurons_p0.4_k4_keep0.0125_power16_minsize150_cut0.15.xlsx")

KMENeuron <- select(KMENeuron, Symbol : moduleLabel)
colnames(KMENeuron) <- c("Gene","GeneName", "moduleColor", "moduleLabel")
ourDataNeuron <- merge(KMENeuron, ruvNormDataNeuron, by = ("Gene"))

#write.csv(ourDataNeuron, "dataImputModulePreservationAnalysisNeuron.csv", row.names = FALSE)

```


```{r message=FALSE, eval=FALSE}
#Alisson's data

Data = read_delim("D:/estagio/WGCNA_analysis/data_comparison/GSE67528_alissonData/GSE67528_Processed_data_htseqcount_83samples.txt", 
    " ", escape_double = FALSE, trim_ws = TRUE)
 marchettoData = Data %>% select(ensembl_gene_id, starts_with("Neuron"));

 variance <- apply(marchettoData[2:26],1,sd)/apply(marchettoData[2:26],1,mean)
hist(variance)
keep=as.data.frame(marchettoData)
rownames(keep)=keep[,1]
keep=keep[2:26]
keep2=which(apply(keep,1,sd)/apply(keep,1,mean)>= 0.3)
keep=keep[keep2,]
hist(keep)
keep3= mutate(keep, ensembl_gene_id=rownames(keep))
marchettoData=keep3

```


```{r message=FALSE, eval=FALSE, include=FALSE}
 ####RUVseq normalization#####
#run deseq to find non-Degs
dds <- DESeqDataSetFromMatrix(countData = countData50, colData = sampleData50, design = ~ condition)

#set which group is the reference group
dds$condition <- relevel(dds$condition, ref="C")
ddsdeseq <- DESeq(dds)
res <- results(ddsdeseq)
summary(res)
res <- as.data.frame(res)
nDEGs_deseq <- subset (res, res$pvalue>=0.4)
nDEGs_deseq <- rownames(nDEGs_deseq)


#overlap nonDEGs and HKgenes
HKgenes <- intersect(HKgenes_full$Ensembl_biomart, rownames(countData50))

nDEGs_HKgenes <- intersect(nDEGs_deseq,HKgenes)


#RUVseq
controlGenes <- nDEGs_HKgenes
RUV <- RUVg(as.matrix(countData50), controlGenes, k=4)

W <- as.data.frame (RUV$W)
N4 <- RUV$normalizedCounts
```

#Module preservation analysis Neurons VS Marchetto data

#Reading neuron data
```{r message=FALSE, eval=FALSE}
dat0 = ourDataNeuron
names(dat0)
# this contains information on the genes
datSummaryNeuron=dat0[,c(1:4)] #CHECAR O COMANDO datSummaryNeuron=dat0[,c(1:3, 23)]
# the following data frame contains
# the gene expression data: columns are genes, rows are arrays (samples)
datExprNeuron <- t(dat0[,5:22])
no.samples <- dim(datExprNeuron)[[1]]
dim(datExprNeuron)
# Set the columns names to probe names
colnames(datExprNeuron) = datSummaryNeuron$Gene
# This module assignment was obtained by Ghazalpour et al
colorsNeuron = dat0$moduleColor

```

# Reading Marchetto Data
```{r message=FALSE, eval=FALSE}

dataMarchetto = marchettoData
datExprMarche = t(dataMarchetto[1:25]);
colnames(datExprMarche) = dataMarchetto$ensembl_gene_id

setLabels = c("Neuron", "Marchetto");
multiExpr = list(Neuron = list(data = datExprNeuron), Marchetto = list(data = datExprMarche));
multiColor = list(Neuron = colorsNeuron);
```

#Running WGCNA module preservation analysis
```{r message=FALSE, eval=FALSE}

system.time( {
mp = modulePreservation(multiExpr, multiColor,
referenceNetworks = 1,
nPermutations = 200,
randomSeed = 1,
quickCor = 0,
verbose = 3)
} );

# Save the results
save(mp, file = "modulePreservationNeuronMarchetto.RData");

#Alternatively, if the data has already been calculated before, load them from disk:
#load(file="modulePreservationNeuronNPC.RData")

```

#Analysis and display of module preservation results
```{r message=FALSE, eval=FALSE}

ref = 1
test = 2
statsObs = cbind(mp$quality$observed[[ref]][[test]][, -1], mp$preservation$observed[[ref]][[test]][, -1])
statsZ = cbind(mp$quality$Z[[ref]][[test]][, -1], mp$preservation$Z[[ref]][[test]][, -1]);

# Compare preservation to quality:
print( cbind(statsObs[, c("medianRank.pres", "medianRank.qual")],
signif(statsZ[, c("Zsummary.pres", "Zsummary.qual")], 2)) )
```

#Plotting results
```{r message=FALSE, eval=FALSE}
# Module labels and module sizes are also contained in the results
modColors = rownames(mp$preservation$observed[[ref]][[test]])
moduleSizes = mp$preservation$Z[[ref]][[test]][, 1];
# leave grey and gold modules out
plotMods = !(modColors %in% c("grey", "gold"));
# Text labels for points
text = modColors[plotMods];
# Auxiliary convenience variable
plotData = cbind(mp$preservation$observed[[ref]][[test]][, 2], mp$preservation$Z[[ref]][[test]][, 2])
# Main titles for the plot
mains = c("Preservation Median rank", "Preservation Zsummary");
# Start the plot
sizeGrWindow(10, 5);
pdf(file ="NeuronsvsMarchettoModulePreservation-Zsummary-medianRank.pdf", wi=10, h=5)
par(mfrow = c(1,2))
par(mar = c(4.5,4.5,2.5,1))
for (p in 1:2)
{
min = min(plotData[, p], na.rm = TRUE);
max = max(plotData[, p], na.rm = TRUE);
# Adjust ploting ranges appropriately
if (p==2)
{
if (min > -max/10) min = -max/10
ylim = c(min - 0.1 * (max-min), max + 0.1 * (max-min))
} else
ylim = c(max + 0.1 * (max-min), min - 0.1 * (max-min))
plot(moduleSizes[plotMods], plotData[plotMods, p], col = 1, bg = modColors[plotMods], pch = 21,
main = mains[p],
cex = 2.4,
ylab = mains[p], xlab = "Module size", log = "x",
ylim = ylim,
xlim = c(10, 2000), cex.lab = 1.2, cex.axis = 1.2, cex.main =1.4)
labelPoints(moduleSizes[plotMods], plotData[plotMods, p], text, cex = 1, offs = 0.08);
# For Zsummary, add threshold lines
if (p==2)
{
abline(h=0)
abline(h=2, col = "blue", lty = 2)
abline(h=10, col = "darkgreen", lty = 2)
}
}
# If plotting into a file, close it
dev.off();
```

```{r message=FALSE, eval=FALSE}
# Re-initialize module color labels and sizes
modColors = rownames(statsZ)
moduleSizes = mp$quality$Z[[ref]][[test]][, 1];
# Exclude improper modules
plotMods = !(modColors %in% c("grey", "gold"));
# Create numeric labels for each module
labs = match(modColors[plotMods], standardColors(50));
# Start the plot: open a suitably sized graphical window and set sectioning and margins.
sizeGrWindow(12, 9);
par(mfrow = c(3,5))
par(mar = c(3,3,2,1))
par(mgp = c(1.6, 0.4, 0));
# Plot each Z statistic in a separate plot.
for (s in 1:ncol(statsZ))
{
min = min(statsZ[plotMods, s], na.rm = TRUE);
max = max(statsZ[plotMods, s], na.rm = TRUE);
if (min > -max/5) min = -max/5
plot(moduleSizes[plotMods], statsZ[plotMods, s], col = 1, bg = modColors[plotMods], pch = 21,
main = colnames(statsZ)[s],
cex = 1.7,
ylab = colnames(statsZ)[s], xlab = "Module size", log = "x",
ylim = c(min - 0.1 * (max-min), max + 0.1 * (max-min)),
xlim = c(20, 1000))
labelPoints(moduleSizes[plotMods], statsZ[plotMods, s], labs, cex = 0.7, offs = 0.04);
abline(h=0)
abline(h=2, col = "blue", lty = 2)
abline(h=10, col = "darkgreen", lty = 2)
}

data.frame(color = modColors[plotMods], label = labs)
```